export AUTH0_DOMAIN="cpresource.us.auth0.com"
export AUTH0_API_IDENTIFIER="mvr_api"
export AUTH0_CLIENT_ID="G3qXpdP3nJcfu0xEBz3iBMhKc8nh93Zh"
export AUTH0_CALLBACK_URI="http://127.0.0.1:5000"
export AUTH0_AUTHORIZE_URL="https://$AUTH0_DOMAIN/authorize?audience=$AUTH0_API_IDENTIFIER&response_type=token&client_id=$AUTH0_CLIENT_ID&redirect_uri=$AUTH0_CALLBACK_URI"