"""empty message

Revision ID: 8c2900288bed
Revises: c55a11694f27
Create Date: 2021-02-14 15:32:01.765303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2900288bed'
down_revision = 'c55a11694f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_relationships', sa.Column(
        'membership_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('member_relationships_membership_type_fkey', 'member_relationships', type_='foreignkey')
    op.create_foreign_key(None, 'member_relationships', 'membership_types', ['membership_type_id'], ['id'])
    op.drop_column('member_relationships', 'membership_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_relationships', sa.Column('membership_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'member_relationships', type_='foreignkey')
    op.create_foreign_key('member_relationships_membership_type_fkey', 'member_relationships', 'membership_types', ['membership_type'], ['id'])
    op.drop_column('member_relationships', 'membership_type_id')
    # ### end Alembic commands ###
