"""empty message

Revision ID: c86cdd833757
Revises: 6ad51872d690
Create Date: 2021-02-11 21:15:49.052096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86cdd833757'
down_revision = '6ad51872d690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_constraint('customer_relationships_business_id_fkey', 'customer_relationships', type_='foreignkey')
    op.create_foreign_key(None, 'customer_relationships', 'businesses', ['business_id'], ['id'])
    op.drop_table('companies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_relationships', type_='foreignkey')
    op.create_foreign_key('customer_relationships_business_id_fkey', 'customer_relationships', 'companies', ['business_id'], ['id'])
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='companies_pkey')
    )
    op.drop_table('businesses')
    # ### end Alembic commands ###
